Deps: Update faithfuls <easy-as-pypi>
- Source: easy-as-pypi @ 7a8e6f851512

- Commit generated by:

    https://github.com/thegittinsgood/git-update-faithful#⛲

  under the guidance of:

    https://github.com/doblabs/easy-as-pypi/blob/release/bin/update-faithful

diff --git a/.github/bin/update-poetry b/.github/bin/update-poetry
--- a/.github/bin/update-poetry
+++ b/.github/bin/update-poetry
@@ -19,24 +19,22 @@ UPDEPS_REPO_ORG_PROJ="${UPDEPS_REPO_ORG_PROJ}"
 
 # Cascade options.
 # - Whether to repository_dispatch after PR completes.
-UPDEPS_CASCADE_INHIBIT="${UPDEPS_CASCADE_INHIBIT:-false}"
-# - The cascade_versioning value to send on repository_dispatch.
-#   - Also what update-merged.yml uses when versioning current project.
-#   - Also what determines if we poetry-update pre-release assets, see below.
-UPDEPS_CASCADE_VERSIONING="${UPDEPS_CASCADE_VERSIONING:-alpha}"
+UPDEPS_CASCADE_INHIBIT="${UPDEPS_CASCADE_INHIBIT:-true}"
 # - The cascade_updatedeps value to send on repository_dispatch.
 #   - Also what to po-update: "our" deps, or "all" (incl. 3rd-party), see below.
 #   - There's another option, "skip", but then this script is not called.
-UPDEPS_CASCADE_UPDATEDEPS="${UPDEPS_CASCADE_UPDATEDEPS:-all}"
+UPDEPS_CASCADE_UPDATEDEPS="${UPDEPS_CASCADE_UPDATEDEPS:-skip}"
+# - The cascade_versioning value to send on repository_dispatch.
+#   - Also what update-merged.yml uses when versioning current project.
+#   - Also what determines if we poetry-update pre-release assets, see below.
+UPDEPS_CASCADE_VERSIONING="${UPDEPS_CASCADE_VERSIONING:-skip}"
 
 # Calculated value. Caller can specify explicitly (UPDEPS_INCLUDE_PRERELEASE)
 # or we'll figure it out.
 UPDEPS_INCLUDE_PRERELEASE="$(
   (${UPDEPS_INCLUDE_PRERELEASE:-false} \
-   || (! ${UPDEPS_CASCADE_INHIBIT} \
-       && (false \
-           || [ "${UPDEPS_CASCADE_VERSIONING}" = "least" ] \
-           || [ "${UPDEPS_CASCADE_VERSIONING}" = "alpha" ]))) \
+   || [ "${UPDEPS_CASCADE_VERSIONING}" = "alpha" ] \
+   || [ "${UPDEPS_CASCADE_VERSIONING}" = "least" ]) \
   && echo true \
   || echo false
 )"
@@ -53,8 +51,9 @@ UPDEPS_FAKE_UPDATE="${UPDEPS_FAKE_UPDATE:-false}"
 __UPDEPS__CPYST__="
   UPDEPS_FAKE_UPDATE=true \
   UPDEPS_CASCADE_INHIBIT=true \
-  UPDEPS_CASCADE_VERSIONING=skip \
   UPDEPS_CASCADE_UPDATEDEPS=skip \
+  UPDEPS_CASCADE_VERSIONING=skip \
+  UPDEPS_INCLUDE_PRERELEASE=false \
     ./.github/bin/update-poetry
 "
 
@@ -150,8 +149,8 @@ UPDEPS_PR_TITLE="${UPDEPS_PR_TITLE:-Build: Update deps}"
 #  UPDEPS_CASCADE_INHIBIT=${UPDEPS_CASCADE_INHIBIT}
 #  UPDEPS_FAKE_UPDATE=${UPDEPS_FAKE_UPDATE}
 UPDEPS_PR_BODY="${UPDEPS_PR_BODY:-Called with:
-  UPDEPS_CASCADE_VERSIONING=${UPDEPS_CASCADE_VERSIONING}
   UPDEPS_CASCADE_UPDATEDEPS=${UPDEPS_CASCADE_UPDATEDEPS}
+  UPDEPS_CASCADE_VERSIONING=${UPDEPS_CASCADE_VERSIONING}
 }"
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -185,14 +184,18 @@ _updeps_insist_cmd () {
 
   >&2 echo "ERROR: Missing system command ‘${cmdname}’."
 
-  exit 1
+  exit_1
 }
 
 # Program prints a single "true" or "false" to stdout for CI workflow.
 # - Program prints other trace/progress messages to stderr for you ᵒᴥᵒ.
 print_prog () {
-  # SAVVY: %b, not %s, so \n'ewlines and the like honored.
-  >&2 printf "%b" "$@"
+  if [ -z "$1" ]; then
+    >&2 echo
+  else
+    # SAVVY: %b, not %s, so \n'ewlines and the like honored.
+    >&2 printf "%b" "$@"
+  fi
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
@@ -213,30 +216,35 @@ update_poetry_update () {
 
   local has_changes=false
 
+  # CXREF: poetry_update_lock_normal
   if update_and_commit_lock_normal "${branch_name}"; then
     has_changes=true
   fi
 
+  # CXREF: poetry_update_lock_prerelease
   if update_and_commit_lock_prerelease "${branch_name}"; then
     has_changes=true
   fi
 
+  local NEW_PR_URL=""
+
   if ${has_changes}; then
     push_branch "${branch_name}" "${remote_name}"
 
-    local NEW_PR_URL
+    # Set NEW_PR_URL
     gh_pr_create_and_auto_merge_when_checks_finish
 
     resume_old_branch_and_cleanup "${branch_name}"
-
-    # E.g., https://github.com/doblabs/easy-as-pypi/pull/51
-    echo "$(basename "${NEW_PR_URL}")"
   else
     # Aka, "po-update was a no-op\n"
     print_prog "po-up was a no-op\n"
   fi
 
   command rm "${POETRY_OUTPUT_DUMP}"
+
+  # Print just the PR number for update-deps.yml to use as GITHUB_OUTPUT.
+  # - E.g., Prints "51" from https://github.com/doblabs/easy-as-pypi/pull/51
+  printf "%s" "$(basename "${NEW_PR_URL}")"
 }
 
 # ***
@@ -251,6 +259,8 @@ update_and_commit_lock_normal () {
   assert_git_status_only_poetry_lock_changed_if_any
 
   if test -n "$(git status --porcelain=v1)"; then
+    print_prog "✓ normal changes!\n"
+
     prepare_branch "${branch_name}"
 
     poetry_update_commit_changes_normal
@@ -275,14 +285,16 @@ update_and_commit_lock_prerelease () {
   local pyproject_dir
   pyproject_dir="$(make_inspect_var "PYPROJECT_PRERELEASE_DIR")"
 
-  poetry_update_lock_prerelease
+  poetry_update_lock_prerelease "${pyproject_dir}"
 
-  assert_git_status_0_1_or_2_changes
+  assert_git_status_3_or_fewer_changes
 
   assert_git_status_only_prerelease_pyproject_and_or_lock_changed_if_any \
     "${pyproject_dir}"
 
   if test -n "$(git status --porcelain=v1)"; then
+    print_prog "✓ pre-release changes!\n"
+
     prepare_branch "${branch_name}"
 
     poetry_update_commit_changes_prerelease "${pyproject_dir}"
@@ -337,31 +349,44 @@ poetry_update_lock_normal () {
       >&2 echo "GAFFE: Impossible path"
 
       # D_b_C: This execution is kaput, by the laws of Design by Contract.
-      exit 1
+      exit_1
     fi
   else
-    print_prog "fake... "
+    print_prog "fake "
 
     # UPDEPS_FAKE_UPDATE is a faker to make GH Actions CI testing quicker.
-    echo "# This line generated by poetry-update-faker" >> poetry.lock
+    echo "# This line generated by poetry-update-faker" >> "poetry.lock"
   fi
 
   print_prog "✓\n"
 }
 
 poetry_update_lock_prerelease () {
-  print_prog "poetry update...  # pre-release"
+  local pyproject_dir="$1"
 
-  # Create <dir>/pyproject.toml and <dir>/poetry.lock, each copied
-  # from project root and then edited or updated.
-  # - The pre-release toml and lock are identical to the normal
-  #   project files, expect "our" deps are updated to whatever's
-  #   on test.PyPI — and it's expected that anyone who installs
-  #   the pre-release package will install using something like:
-  #     pip --index-url https://test.pypi.org/simple \
-  #       --extra-index-url=https://pypi.org/simple/ \
-  #       <pkg>
-  make prepare-poetry-prerelease >> "${POETRY_OUTPUT_DUMP}"
+  print_prog "poetry update: pre-release... "
+
+  if ! ${UPDEPS_FAKE_UPDATE:-false}; then
+    # Create <dir>/pyproject.toml and <dir>/poetry.lock, each copied
+    # from project root and then edited or updated.
+    # - The pre-release toml and lock are identical to the normal
+    #   project files, expect "our" deps are updated to whatever's
+    #   on test.PyPI — and it's expected that anyone who installs
+    #   the pre-release package will install using something like:
+    #     pip --index-url https://test.pypi.org/simple \
+    #       --extra-index-url=https://pypi.org/simple/ \
+    #       <pkg>
+    make prepare-poetry-prerelease >> "${POETRY_OUTPUT_DUMP}" 2>&1
+  else
+    print_prog "fake "
+
+    # UPDEPS_FAKE_UPDATE is a faker to make GH Actions CI testing quicker.
+    if [ -d "${pyproject_dir}" ]; then
+      echo "# This line generated by poetry-update-faker" >> "${pyproject_dir}/poetry.lock"
+    fi
+  fi
+
+  print_prog "✓\n"
 }
 
 # ***
@@ -411,6 +436,8 @@ prepare_branch () {
 
   git checkout -q -b "${branch_name}" "${scoped_head}"
 
+  _CHANGED_BRANCH="${branch_name}"
+
   # Prepare for commit if running on CI.
   if ${CI:-false}; then
     git config user.email "${UPDEPS_USER_EMAIL}"
@@ -423,6 +450,8 @@ resume_old_branch_and_cleanup () {
 
   git checkout -q -
 
+  _CHANGED_BRANCH=""
+
   # Delete local branch when this script is run from user terminal (not from GHA).
   # - SAVVY: Use 'CI' environ to detect CI environment — this is the first
   #   environ that GH documents. Other candidates include 'GITHUB_ACTIONS'
@@ -430,29 +459,20 @@ resume_old_branch_and_cleanup () {
   #   - REFER:
   # https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables
   if ! ${CI:-false}; then
-    # FIXME: Might need Big D.
     # Ignore stderr message that -q doesn't inhibit:
     #   warning: deleting branch 'foo' that has been merged to
     #            'refs/remotes/origin/foo', but not yet merged to HEAD.
-    git branch -q -d "${branch_name}" 2> /dev/null
+    git branch -q -D "${branch_name}" 2> /dev/null
   fi
 }
 
 poetry_update_commit_changes () {
   local commit_message="$1"
 
-  if ${UPDEPS_INCLUDE_PRERELEASE} \
-    && has_changes_pyproject_toml \
-  ; then
-    print_prog "git add pyproject.toml\n"
+  git_add_if_changed "poetry.lock"
 
-    git add pyproject.toml
-  fi
-
-  if has_changes_poetry_lock; then
-    print_prog "git add poetry.lock\n"
-
-    git add poetry.lock
+  if ${UPDEPS_INCLUDE_PRERELEASE}; then
+    git_add_if_changed "pyproject.toml"
   fi
 
   print_prog "git commit... "
@@ -490,7 +510,7 @@ push_branch () {
   local branch_name="$1"
   local remote_name="$2"
 
-  print_prog "git push '${remote_name}'... "
+  print_prog "git push -q -u '${remote_name}' HEAD:refs/heads/${branch_name}... "
 
   # Even though --quiet, any message from the remote is printed to stderr, e.g.,:
   #   remote:
@@ -506,7 +526,14 @@ push_branch () {
   # workflow to run. (The normal GH_TOKEN=${{ github.token }} inhibits
   # workflow events.)
 
-  git push -q -u ${remote_name} "HEAD:refs/heads/${branch_name}" 2> /dev/null
+  local git_output
+
+  if ! git_output="$(git push -q -u "${remote_name}" "HEAD:refs/heads/${branch_name}" 2>&1)"; then
+    >&2 echo -e "\n\nERROR: git-push failed:"
+    echo "${git_output}" | >&2 sed 's/^/  /'
+
+    exit_1
+  fi
 
   print_prog "✓\n"
 }
@@ -517,22 +544,29 @@ push_branch () {
 # - We don't default to the sole remote if that's all there is.
 #   We're looking for a specific github.com/<org>/<proj> remote.
 git_upstream_remote () {
-  if [ -z "${UPDEPS_REPO_ORG_PROJ}" ]; then
+  local updeps_repo_org_proj
+
+  if [ -n "${UPDEPS_REPO_ORG_PROJ}" ]; then
+    updeps_repo_org_proj="${UPDEPS_REPO_ORG_PROJ}"
+  else
     local repo_url
 
-    repo_url="$(print_upstream_remote_url)" || exit 1
+    repo_url="$(print_upstream_remote_url)" || exit_1
 
     if [ -n "${repo_url}" ]; then
       # Trim, e.g., https://github.com/doblabs/easy-as-pypi → doblabs/easy-as-pypi
+      # - Also trim comments, e.g., doblabs/easy-as-pypi#🥧 → doblabs/easy-as-pypi
       # - Result is same as ${{ github.repository }}
-      UPDEPS_REPO_ORG_PROJ="$(
-        echo "${repo_url}" | sed 's#^.*/\([^/]*/[^/]*\)$#\1#'
+      updeps_repo_org_proj="$(
+        echo "${repo_url}" \
+          | sed 's#^.*/\([^/]*/[^/]*\)$#\1#' \
+          | sed 's/\([^#]*\).*/\1/'
       )"
 
-      if [ -z "${UPDEPS_REPO_ORG_PROJ}" ]; then
+      if [ -z "${updeps_repo_org_proj}" ]; then
         >&2 echo "ERROR: Could not deduce project repo from URL: ${repo_url}"
 
-        exit 1
+        exit_1
       fi
     else
       >&2 echo "ERROR: Could not deduce remote URL from remotes or pyproject.toml"
@@ -540,20 +574,28 @@ git_upstream_remote () {
       >&2 echo "  from [tool.poetry] or [tool.poetry.urls]"
       >&2 echo "- Check \`git remote get-url origin\`"
 
-      exit 1
+      exit_1
     fi
   fi
 
-  if ! git_upstream_remote_deduce; then
+  # ***
+
+  local upstream_remote
+
+  if ! upstream_remote="$(git_upstream_remote_deduce "${updeps_repo_org_proj}")" \
+    || [ -z "${upstream_remote}" ] \
+  ; then
     # Note that we're ignoring the tracking branch. We want our GH
     # org/proj repo. Which we didn't find.
     >&2 echo "ERROR: Could not determine the upstream GitHub remote"
-    >&2 echo "- We checked UPDEPS_REPO_ORG_PROJ (“${UPDEPS_REPO_ORG_PROJ}”)"
+    >&2 echo "- We checked UPDEPS_REPO_ORG_PROJ (“${updeps_repo_org_proj}”)"
     >&2 echo "  against these remotes:"
-    >&2 echo git remote -v
+    >&2 git remote -v
 
-    exit 1
+    exit_1
   fi
+
+  printf "%s" "${upstream_remote}"
 }
 
 print_upstream_remote_url () {
@@ -570,7 +612,7 @@ print_upstream_remote_url_from_pyproject_toml () {
     >&2 echo "- Please run from venv with \`tomlq\` installed"
     >&2 echo "- Or set the 'UPDEPS_REPO_ORG_PROJ' environ"
 
-    exit 1
+    exit_1
   fi
 
   # REFER: https://github.com/jqlang/jq/issues/354
@@ -587,15 +629,17 @@ print_upstream_remote_url_from_pyproject_toml () {
     >&2 echo "  from [tool.poetry] or [tool.poetry.urls]"
     >&2 echo "- You can also set 'UPDEPS_REPO_ORG_PROJ' environ directly"
 
-    exit 1
+    exit_1
   fi
 }
 
 git_upstream_remote_deduce () {
+  local updeps_repo_org_proj="$1"
+
   git remote -v \
     | grep \
-        -e "[[:space:]]git@.*:${UPDEPS_REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
-        -e "github.com/${UPDEPS_REPO_ORG_PROJ}\(\.git\)\? (push)\$" \
+        -e "[[:space:]]git@.*:${updeps_repo_org_proj}\(\.git\)\? (push)\$" \
+        -e "github.com/${updeps_repo_org_proj}\(\.git\)\? (push)\$" \
     | sed 's/^\([^[:space:]]\+\).*/\1/'
 }
 
@@ -641,8 +685,8 @@ gh_pr_create_and_auto_merge_when_checks_finish () {
 
   if [ -s "${POETRY_OUTPUT_DUMP}" ]; then
     print_prog
-    print_prog "poetry dump:"
-    print_prog "${POETRY_OUTPUT_DUMP} | sed 's/^/  /'"
+    print_prog "poetry dump:\n"
+    print_prog "$(cat "${POETRY_OUTPUT_DUMP}" | sed 's/^/  /')\n"
     print_prog
   fi
 
@@ -821,7 +865,7 @@ assert_git_email_known_ci () {
 
   >&2 echo "ERROR: Please set UPDEPS_USER_EMAIL organization or project variable"
 
-  exit 1
+  exit_1
 }
 
 assert_git_email_known_interactive () {
@@ -830,7 +874,7 @@ assert_git_email_known_interactive () {
 
   >&2 echo "ERROR: Who are you? \`git config user.email\` says you're nobody"
 
-  exit 1
+  exit_1
 }
 
 # ***
@@ -841,7 +885,7 @@ assert_git_status_tidy () {
 
   >&2 echo "ERROR: $(basename "$0") requires a tidy repo"
 
-  exit 1
+  exit_1
 }
 
 # ***
@@ -851,8 +895,8 @@ assert_git_status_0_or_1_changes () {
   assert_git_status_changes_le_max 1
 }
 
-assert_git_status_0_1_or_2_changes () {
-  assert_git_status_changes_le_max 2
+assert_git_status_3_or_fewer_changes () {
+  assert_git_status_changes_le_max 3
 }
 
 assert_git_status_changes_le_max () {
@@ -863,7 +907,7 @@ assert_git_status_changes_le_max () {
 
   >&2 echo "ERROR: Unexpected: More than ${max} file(s) changed by poetry-update?!"
 
-  exit 1
+  exit_1
 }
 
 # ***
@@ -882,69 +926,156 @@ assert_git_status_only_poetry_lock_changed_if_any () {
   >&2 echo "ERROR: Unexpected: poetry.lock is not sole change after poetry-update?!"
   >&2 echo "${git_status}"
 
-  exit 1
+  exit_1
 }
 
 assert_git_status_only_prerelease_pyproject_and_or_lock_changed_if_any () {
+  # Aka, PYPROJECT_PRERELEASE_DIR
   local pyproject_dir="$1"
 
-  local git_status
-  git_status="$(cd "${pyproject_dir}" && git status --porcelain=v1)"
-
-  test -z "${git_status}" \
+  ! test -d "${pyproject_dir}" \
     && return 0 || true
 
-  local expect_if_both_changed="\
- M poetry.lock
- M pyproject.toml"
+  # ***
 
-  if [ "${git_status}" = " M poetry.lock" ] \
-    || [ "${git_status}" = " M pyproject.toml" ] \
-    || [ "${git_status}" = "${expect_if_both_changed}" ] \
-  ; then
+  local git_status
+  git_status="$(cd "${pyproject_dir}" && git_status_short)"
+
+  if [ -z "${git_status}" ]; then
 
     return 0
   fi
 
+  # ***
+
+  local expect_if_all_uncommitted="?? ./"
+  if [ "${git_status}" = "${expect_if_all_uncommitted}" ]; then
+
+    return 0
+  fi
+
+  # ***
+
+  local stripped_status="$(
+    echo "${git_status}" \
+      | sed \
+        -e '/^\( M\|??\) poetry.lock$/d' \
+        -e '/^\( M\|??\) pyproject.toml$/d' \
+        -e '/^\( M\|??\) src$/d' \
+  )"
+
+  if [ -z "${stripped_status}" ]; then
+
+    return 0
+  fi
+
+  # ***
+
   # Should be unreachable path.
-  >&2 echo "ERROR: Unexpected: Something other than pyproject.toml or poetry.lock"
-  >&2 echo "                   has changes after poetry-update?!"
+  >&2 echo "ERROR: Unexpected: Something other than pyproject.toml, poetry.lock,"
+  >&2 echo "                   or src/ has changes after poetry-update?!"
   >&2 echo "${git_status}"
 
-  exit 1
+  exit_1
 }
 
 # ***
 
-has_changes_poetry_lock () {
-  has_unstaged_changes "poetry.lock"
+git_add_if_changed () {
+  local filename="$1"
+
+  if has_unstaged_changes "${filename}"; then
+    print_prog "git add ${filename}\n"
+
+    git add "${filename}"
+  fi
 }
 
-has_changes_pyproject_toml () {
-  has_unstaged_changes "pyproject.toml"
+# Note we use `git status --short`, not `git status --porcelain=v1`,
+# because the latter ignores status.relativePaths and always shows
+# paths relative to the repository root. But rather than pass around
+# pyproject_dir, we just assume the current working directory is either
+# project root or pyproject_dir, and then we rely on status.relativePaths
+# so our status-checkers don't have to worry about directory paths.
+#
+# Note that git-status docs make it sound like --short might break
+# between versions or between environments, but I'd like to see that,
+# especially when we force the config value at ruuntime.
+git_status_short () {
+  git -c status.relativePaths=true status --short
 }
 
 has_unstaged_changes () {
   local filename="$1"
 
+  local git_status
+  git_status="$(git_status_short)"
+
+  if [ "$(git_status_short)" = "?? ./" ] \
+    && [ -f "${filename}" ]; then
+
+    return 0
+  fi
+
+  # ***
+
   local modified_file
 
   while IFS= read -r modified_file; do
-    test "${modified_file}" = " M ${filename}" \
-      && return 0 || true
-  done <<< "$(git status --porcelain=v1)"
+    if [ "${modified_file}" = " M ${filename}" ] \
+      || [ "${modified_file}" = "?? ${filename}" ] \
+    ; then
+      
+      return 0
+    fi
+  done <<< "${git_status}"
 
   return 1
 }
 
 # +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ #
 
+_NORMAL_EXIT=false
+
+exit_1 () {
+  _NORMAL_EXIT=true
+
+  exit 1
+}
+
+exit_0 () {
+  _NORMAL_EXIT=true
+
+  exit 0
+}
+
+_CHANGED_BRANCH=""
+
+exit_cleanup () {
+  if [ -n "${_CHANGED_BRANCH}" ]; then
+    resume_old_branch_and_cleanup "${_CHANGED_BRANCH}"
+  fi
+
+  if ! ${_NORMAL_EXIT}; then
+    # Dev: Unexpected error path occurred, you might wanna graceify.
+    >&2 echo "ALERT: ${PROG_NAME} exited abnormally!"
+    >&2 echo "- Hint: Enable \`set -x\` and run again..."
+  fi
+}
+
+# ***
+
 main () {
   set -e
 
   source_deps
 
+  trap exit_cleanup EXIT
+
   update_poetry_update "$@"
+
+  # Unhook exit_cleanup.
+  trap - EXIT
 }
 
 if [ "$0" = "${BASH_SOURCE[0]}" ]; then
